# Generated by Django 3.2.9 on 2021-11-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211125_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml', models.IntegerField(default=5, verbose_name='重量')),
            ],
            options={
                'verbose_name_plural': '重量',
            },
        ),
    ]
