# Generated by Django 3.2.9 on 2021-11-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_seasoning_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasoning',
            name='measure',
        ),
        migrations.AddField(
            model_name='seasoning',
            name='measure',
            field=models.ManyToManyField(to='api.Measure', verbose_name='重量'),
        ),
    ]
