# Generated by Django 3.2.9 on 2021-11-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211125_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='ml',
            field=models.IntegerField(verbose_name='重量'),
        ),
    ]
