# Generated by Django 3.2.9 on 2021-11-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211125_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='measureName',
            field=models.CharField(default='大さじ', max_length=50, verbose_name='計量の種類'),
        ),
        migrations.RemoveField(
            model_name='seasoning',
            name='measure',
        ),
        migrations.AddField(
            model_name='seasoning',
            name='measure',
            field=models.ManyToManyField(to='api.Measure', verbose_name='重量'),
        ),
    ]
