# Generated by Django 3.2.9 on 2021-11-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211125_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measureName', models.CharField(max_length=50, verbose_name='計量の種類')),
            ],
            options={
                'verbose_name_plural': '計量の種類',
            },
        ),
        migrations.RemoveField(
            model_name='measure',
            name='measureName',
        ),
        migrations.AlterField(
            model_name='measure',
            name='ml',
            field=models.IntegerField(default=10, verbose_name='重量'),
        ),
    ]
