# Generated by Django 3.2.9 on 2021-11-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211125_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='seasoning',
        ),
        migrations.AddField(
            model_name='recipe',
            name='seasoning',
            field=models.ManyToManyField(to='api.Seasoning', verbose_name='調味料'),
        ),
    ]
