# Generated by Django 3.2.9 on 2021-11-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211125_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
