# Generated by Django 3.2.9 on 2021-12-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211207_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Seasoning',
        ),
        migrations.AddField(
            model_name='recipe',
            name='SeasoningName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasoning'),
        ),
    ]
