# Generated by Django 3.2.9 on 2021-12-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20211207_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='seasoningName',
        ),
        migrations.AddField(
            model_name='recipe',
            name='seasoningName',
            field=models.ManyToManyField(to='api.Seasoning', verbose_name='調味料'),
        ),
    ]
