# Generated by Django 3.2.9 on 2021-11-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seasoning',
        ),
        migrations.AddField(
            model_name='recipe',
            name='Measure',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='SeasoningName',
            field=models.CharField(default=0, max_length=100, verbose_name='調味料名'),
            preserve_default=False,
        ),
    ]
