# Generated by Django 3.2.9 on 2021-11-25 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasoning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='調味料名')),
                ('measure', models.IntegerField(default=1, verbose_name='数量')),
            ],
            options={
                'verbose_name_plural': '調味料',
                'db_table': 'seasoning',
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Measure',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='SeasoningName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.seasoning', verbose_name='調味料'),
        ),
    ]
