# Generated by Django 3.2.9 on 2021-11-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211125_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name_plural': 'レシピ'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='SeasoningName',
        ),
        migrations.RemoveField(
            model_name='seasoning',
            name='measure',
        ),
        migrations.AddField(
            model_name='recipe',
            name='seasoning',
            field=models.ManyToManyField(to='api.Seasoning', verbose_name='調味料'),
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipes',
        ),
    ]
