# Generated by Django 3.2.9 on 2021-11-25 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasoning',
            name='measure',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='api.measure', verbose_name='重量'),
        ),
    ]
