# Generated by Django 3.2.9 on 2021-11-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211125_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasoning',
            name='measure',
        ),
        migrations.AddField(
            model_name='seasoning',
            name='measure',
            field=models.IntegerField(default=10, verbose_name='重量'),
        ),
    ]
