# Generated by Django 3.2.9 on 2021-11-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211125_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='measure',
            field=models.IntegerField(default=10),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='seasoning',
        ),
        migrations.AddField(
            model_name='recipe',
            name='seasoning',
            field=models.CharField(default='', max_length=100),
        ),
    ]
