# Generated by Django 3.2.9 on 2021-11-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211125_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HowMeasure',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='measure',
        ),
        migrations.AlterField(
            model_name='seasoning',
            name='measure',
            field=models.IntegerField(default=0, verbose_name='重量'),
        ),
    ]
